(function() {var implementors = {};
implementors["frunk"] = ["impl&lt;CH, CTail&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;<a class=\"enum\" href=\"frunk/coproduct/enum.Coproduct.html\" title=\"enum frunk::coproduct::Coproduct\">Coproduct</a>&lt;CH, CTail&gt;&gt; for <a class=\"enum\" href=\"frunk/coproduct/enum.Coproduct.html\" title=\"enum frunk::coproduct::Coproduct\">Coproduct</a>&lt;CH, CTail&gt;",];
implementors["frunk_core"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;<a class=\"struct\" href=\"frunk_core/hlist/struct.HNil.html\" title=\"struct frunk_core::hlist::HNil\">HNil</a>&gt; for <a class=\"struct\" href=\"frunk_core/hlist/struct.HNil.html\" title=\"struct frunk_core::hlist::HNil\">HNil</a>","impl&lt;H, T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;<a class=\"struct\" href=\"frunk_core/hlist/struct.HCons.html\" title=\"struct frunk_core::hlist::HCons\">HCons</a>&lt;H, T&gt;&gt; for <a class=\"struct\" href=\"frunk_core/hlist/struct.HCons.html\" title=\"struct frunk_core::hlist::HCons\">HCons</a>&lt;H, T&gt;",];
implementors["quote"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.str.html\">str</a>&gt; for <a class=\"struct\" href=\"quote/struct.Tokens.html\" title=\"struct quote::Tokens\">Tokens</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.str.html\">str</a>&gt; for <a class=\"struct\" href=\"quote/struct.Ident.html\" title=\"struct quote::Ident\">Ident</a>",];
implementors["syn"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.str.html\">str</a>&gt; for <a class=\"struct\" href=\"syn/struct.Ident.html\" title=\"struct syn::Ident\">Ident</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
